Repository Dev-On-Play/spring-project, pull requests merged in 2024-05, with the labels that each got.

#68 [BE] Member 관련 기본 API 구현
  backend/src/main/java/mos/contents/dto/CommentResponse.java
  backend/src/main/java/mos/member/controller/MemberController.java
  backend/src/main/java/mos/member/dto/MemberResponse.java
  backend/src/main/java/mos/member/dto/UpdateMemberRequest.java
  backend/src/main/java/mos/member/entity/Member.java
  backend/src/main/java/mos/member/repository/MemberRepository.java
  backend/src/main/java/mos/member/service/MemberService.java
  backend/src/main/java/mos/mogako/dto/MogakoResponse.java
  backend/src/test/java/mos/integration/MemberIntegrationTest.java
  backend/src/test/java/mos/member/entity/MemberTest.java
  backend/src/test/java/mos/member/service/MemberServiceTest.java
Labels: BE, feature

#64 [FE] 모각코 생성 페이지 구현
  frontend/app/create/page.tsx
  frontend/app/mypage/page.tsx
  frontend/components/common/Calendar.tsx
Labels: FE

#69 [FE] feat: 카테고리 버튼 필터 검색 구현
  frontend/app/mainPage/exampleDatas/cardViewExData.json
  frontend/app/mainPage/page.tsx
  frontend/components/main-page/categoryButton.tsx
  frontend/components/main-page/mogakoCard.tsx
Labels: feature, FE

#76 [BE] 배포 서버 내 CORS 이슈 해결
  backend/src/main/java/mos/config/WebMvcConfiguration.java
  backend/src/main/java/mos/member/controller/MemberController.java
Labels: BE, feature
